name=sink-connector-snowflake-users-v3
connector.class=com.snowflake.kafka.connector.SnowflakeStreamingSinkConnector
tasks.max=1

# Source Kafka topic (matching Debezium CDC topic)
topics=postgres-source-1.public.users

# Snowflake Account & Connection Details
snowflake.url.name=GWEKWZX-CZ48845.snowflakecomputing.com
snowflake.user.name=dbt_service_user
snowflake.role.name=TRANSFORMER_DEV
snowflake.private.key=MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDOEfBrr5CdYCORSPaIzhIItUOpo7oYOIQj2KNiDnQ7Y5eq6vNw5h0NFTYHseIFz6ggyeZsBlffPjONz8ri8MQRmZ/FD4OQSgp1JmGFlflnRtIX35zJrG6yZXGwhYRst8tukWH3L7Ba5ck2AH5bTv+5oaT1l8kfOekp9fZCThDaMuSt/hhaM2jv/wdA3eJiQ2CAzzgeh08ozHKYH+NGdCn8928rLsU8OpDDGvGIn1TjGhIDHoUW7SAkG9xK8GxanIBorfxgWkEDOibSFx/fKM4IHPjWHEcdCBx3ja9mY+hp/uqeNsB5UDL9WchDtAgG1WSIjl1ne5eQ63Km6iKd1V89AgMBAAECggEAKzee7O6qjR7bBr6/GYziQlpFoP+56Rd9OwlVppxyavwllE5nFM/l2tcOeEmppd9ZmtrNDO29ow+n/z9LhRHKhQhrdggdZvboP453mG0OG8dCC4i1mKQlqRtWXxd5YNWhAATUf2NMgJu9eapb1al5P0Sz1F/rabWa/VZcuaYmqaPvT8E2aQ4Z+aMpVT85gKD1MonFX8Qruv7UdR+BF/McqKbXTGl/+Efoy+W1/eXzVrdb9UTTTshcZLFR+Df/SBihREqOWYg7Ts/0SgoGVrh4QMg05BnT7bPUUfS4hMsn1Rv5uxjLtoEb8O004rjVceblVtRxKs+Z6ZYU7WdVxLjG7wKBgQDybQtufx7VDIlUdUBdQClnwizk9yxbbrhEMaDgFYPhYLEkaD+E21YVmecH4Na5cD9xTxRFmhdTPDPr7QRvCqHCHzJjZoGgkG+J2pA6lRYQ1SUYdkJKWYtqK6RPt7POpTa/ncJW/jTBf+4g5p7yge2G9rKfPow2JiopWU3+2m43FwKBgQDZm8QbDE7F3a7quteD//FaNnGtIirOC0t2h21OBT+UitAkKhitVUzgVseRyXW3/6aaZWgZ48kCuUEPP1k1z8DBRMO2oFbWRpG/SOV/XYWc9nax9oKays+9CcfR9a0eQwevMiNbWQaOQa0SCxHSS3xhvgrdn4nBQtJgBtZB/dvQywKBgASQjRCNkDUOwV83vfiDhsQPYe0Fwm4OTaXrEU5m2U7bFTrMQ7Xqs1pAxZreXuyq8mbdyFHvLtVAYvHkSpsUpisTj01T1skBLzh3RxPzTrEOcl5di63+taNQIw3lNZuEfN1qyQf+TVv/Xqp77S4/yAsshfx9nwI+Abk5l0BfOIgNAoGBAJIQYiOdsUpTMNPSMlMh+wkIvmjuJDlFj5Ox94aFM1YrjuaXcxT1yrJSzYZn6aJl8Zh1NNkb8pLncmofpWvfVYzk8VGmcmNF3xK8hX9mcQcY0DdINgZc1/AVnpCqDVfgukm4p87rBOF76AXSdFXp4UViYLy+F6MnjTpznGGTWnbdAoGBALtWqAEYqtOUiglVzHplKCi69atewHnekWxeFXRAB0lkU8bvRiozWwZ5Pm2nmNaPaWrZl8qOHcLiaBQay8n5E8LzNPm3DDHpRaDMThNs18uqJTl3kav5r0ZUaF/f6qczI6iDT1moidq6c2FSJdoDsQV3WyztWsiqY8SVUnzYtBGv

# Target Snowflake Database & Schema
snowflake.database.name=ELS_SOURCE_SYSTEMS_DB_DEV
snowflake.schema.name=SRC_NHE_INSIGHTS

# Streaming Ingestion & Table Mapping
snowflake.ingestion.method=SNOWPIPE_STREAMING
snowflake.topic2table.map=postgres-source-1.public.users:users_raw

# Schematization & Compatibility Settings (KC v4 Fixes)
snowflake.enable.schematization=false
snowflake.streaming.validate.compatibility.with.classic=false

# Read all historical messages from beginning of the topic
consumer.override.auto.offset.reset=earliest

# Converters for key and value payloads
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false